### ISSUE TITLE
Install trouble

### ISSUE THREAD

**Issue by cmcgarr1** [nash-io/openlimits-python#5]
"WARNING: Requirement 'target/wheels/openlimits_python-0.1.0-cp38-cp38-macosx_10_7_x86_64.whl' looks like a filename, but the file does not exist
ERROR: openlimits_python-0.1.0-cp38-cp38-macosx_10_7_x86_64.whl is not a supported wheel on this platform."

On the last step of the install I run into this error. Any idea what I'm doing wrong?

**Comment by cmcgarr1** [comment]
When I look in the folder target/wheels that file is not in there and there is a different .whl file, openlimits_python-0.1.0-cp37-cp37m-macosx_10_7_x86_64.whl. If I try to install using that whl address instead I get the error, "ERROR: openlimits_python-0.1.0-cp37-cp37m-macosx_10_7_x86_64.whl is not a supported wheel on this platform."

**Comment by notdanilo** [comment]
@cmcgarr1 are you on Mac OS?
